export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_AUTHORS = 'LOAD_AUTHORS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_COURSES_FAIL = 'LOAD_COURSES_FAIL';
export const LOAD_AUTHORS_FAIL = 'LOAD_AUTHORS_FAIL';

export const SAVE_COURSE = 'SAVE_COURSE';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const SAVE_COURSE_FAIL = 'SAVE_COURSE_FAIL';

export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL';
